name: architecture
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.19.0
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  shared_preferences: ^2.0.8
  go_router: ^14.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/icons/

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: es
  arb_dir: lib/config/localization/l10n
  output_dir: lib/config/localization/generated
  template-arb-file: app_es.arb
  output-localization-file: app_localizations.dart



